# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d7af9bc681513f429ec10b744936e45112672925a24975050202629576584f7a5837752421ef5e3d6e2226aa69240dab7f68ff6dfd2143ce4543e5f1a4fd4e9

test:
  secret_key_base: 6df279f23196bfffe84c60941e3f299aa9e25b1f8535496dfecc7be19e7cb25453d75af4c9060996a6eafaffa800fcc1d83b000f4357592575a67e45761018ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
